### ISSUE TITLE
`yarn check` yields a version error when using `react 16.2`

### ISSUE THREAD

**Issue by MustardForBreakfast** [finnfiddle/react-window-size#5]
Steps to reproduce:
run `yarn check` or `yarn install` on a project that uses `react-window-size`

Expected Behavior:
no warnings or errors logged in outpout

Current Behavior:
`error "react-window-size#react@~0.14.8 || ^15.0.0" doesn't satisfy found match of "react@16.2.0"`

everything still seems to function just fine - perhaps the dependency listing just needs to be updated.

**Comment by finnfiddle** [comment]
fixed
